# Generated by Django 5.2.6 on 2025-10-05 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='countries',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='industry',
            fields=[
                ('industry_id', models.AutoField(primary_key=True, serialize=False)),
                ('industry', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='job_type',
            fields=[
                ('job_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_type', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('Date_of_birth', models.DateField()),
                ('phone_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='company_profile',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('company_website', models.URLField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('industry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_board.industry')),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('geo_location', models.CharField(max_length=30)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_board.countries')),
            ],
        ),
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('start_date', models.DateField()),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_board.company_profile')),
                ('industry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_board.industry')),
                ('job_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_board.job_type')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_board.location')),
            ],
        ),
        migrations.AddField(
            model_name='company_profile',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_board.location'),
        ),
    ]
