# Generated by Django 5.2.6 on 2025-10-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id_no',
            field=models.CharField(max_length=20),
        ),
    ]
