# Generated by Django 5.2.6 on 2025-10-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0002_company_profile_updated_at_jobs_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('recruiter', 'Recruiter'), ('candidate', 'Candidate')], default='candidate', max_length=10),
        ),
    ]
