# Generated by Django 5.2.6 on 2025-10-18 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0003_person_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
