# Generated by Django 5.2.6 on 2025-10-19 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0005_alter_person_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='applications',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('jobs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='job_board.jobs')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='job_board.person')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
